##  Public Domain
##
##  OIS_FOUND
##  OIS_INCLUDE_DIR
##  OIS_LIBRARY
##

find_path(OIS_INCLUDE_DIR NAMES OIS/OIS.h PATH_SUFFIXES OIS)
find_library(OIS_LIBRARY NAMES OIS)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OIS DEFAULT_MSG OIS_LIBRARY OIS_INCLUDE_DIR)
mark_as_advanced(OIS_LIBRARY OIS_INCLUDE_DIR)
